server.port=7002
server.stock=https://stock.web.elasticloud.uy/stock/
server.dlocalgo=https://api-sbx.dlocalgo.com/v1/payments/
server.logger=https://login-shop.web.elasticloud.uy/logger/
server.token=ICxxdYAWmYGMxBqBHYxwvEJotcExWHUZ:qKRLqfsYE1LZHS2PvPFPjZM5XUY8HT5Aj11UHUAD